USE [master]
GO

CREATE DATABASE [CountryBoundaries]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CountryBoundaries', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\CountryBoundaries.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CountryBoundaries_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\CountryBoundaries_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [CountryBoundaries] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CountryBoundaries].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CountryBoundaries] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CountryBoundaries] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CountryBoundaries] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CountryBoundaries] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CountryBoundaries] SET ARITHABORT OFF 
GO
ALTER DATABASE [CountryBoundaries] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CountryBoundaries] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CountryBoundaries] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CountryBoundaries] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CountryBoundaries] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CountryBoundaries] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CountryBoundaries] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CountryBoundaries] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CountryBoundaries] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CountryBoundaries] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CountryBoundaries] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CountryBoundaries] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CountryBoundaries] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CountryBoundaries] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CountryBoundaries] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CountryBoundaries] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CountryBoundaries] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CountryBoundaries] SET RECOVERY FULL 
GO
ALTER DATABASE [CountryBoundaries] SET  MULTI_USER 
GO
ALTER DATABASE [CountryBoundaries] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CountryBoundaries] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CountryBoundaries] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CountryBoundaries] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CountryBoundaries] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'CountryBoundaries', N'ON'
GO
ALTER DATABASE [CountryBoundaries] SET QUERY_STORE = OFF
GO
USE [CountryBoundaries]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [CountryBoundaries]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Country](
	[CountryCode] [nvarchar](3) NOT NULL,
	[CountryName] [nvarchar](40) NOT NULL,
	[CountryBorder] [geography] NOT NULL,
 CONSTRAINT [PK_CountryCode] PRIMARY KEY CLUSTERED 
(
	[CountryCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[uspInsertCountry]
(
	@countryCode nvarchar(3),
	@countryName nvarchar(40),
	@CountryBorder nvarchar(max)
)
AS
BEGIN
    SET NOCOUNT ON

	DECLARE @g geography = geography::STGeomFromText(@CountryBorder, 4326);  

    INSERT INTO Country
		(
			CountryCode, 
			CountryName, 
			CountryBorder
		)
    values 
		(
			@countryCode, 
			@countryName, 
			@g
		)
END;
GO
SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET NUMERIC_ROUNDABORT OFF
GO

CREATE SPATIAL INDEX [SX_Country] ON [dbo].[Country]
(
	[CountryBorder]
)USING  GEOGRAPHY_GRID 
WITH (GRIDS =(LEVEL_1 = MEDIUM,LEVEL_2 = MEDIUM,LEVEL_3 = MEDIUM,LEVEL_4 = MEDIUM), 
CELLS_PER_OBJECT = 16, PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [CountryBoundaries] SET  READ_WRITE 
GO
